export const sampleData = [
  {
    id: '1',
    brand: 'Kia',
    name: 'Rio',
    modelYear: '2010',
    mileage: '0-5000km',
    price: '700000',
    transmission: 'auto',
    condition: 'used',
    bodyType: 'sedan',
    fuel: 'petrol',
    color: 'blue',
    countryManufacture: 'usa',
    countryOfOrigin: 'usa',
    expiryDateofReg: new Date('2018-03-21'),
    options: 'Sun Roof , Navigation',
    city: 'Abu Dhabi',
    area: '1 str street',
    createdBy: 'Bob',
    carPhotoURL: '/assests/images/carImage1.png',
    vin: '123',
    interested: [
      {
        id: 'a',
        name: 'Bob',
        photoURL: 'https://randomuser.me/api/portraits/men/20.jpg',
      },
      {
        id: 'b',
        name: 'Tom',
        photoURL: 'https://randomuser.me/api/portraits/men/22.jpg',
      },
    ],
  },
  {
    id: '2',
    brand: 'Ford',
    name: 'Explorer',
    modelYear: '2015',
    mileage: '0-5000km',
    price: '8000000',
    transmission: 'auto',
    condition: 'used',
    bodyType: 'suv',
    fuel: 'petrol',
    color: 'green',
    countryManufacture: 'usa',
    countryOfOrigin: 'usa',
    expiryDateofReg: new Date('2018-03-21'),
    options: 'Alloy Wheel , Cruise Control',
    city: 'Dubai',
    area: '2 str street',
    createdBy: 'Tom',
    carPhotoURL: '/assests/images/carImage2.png',
    vin: '345',
    interested: [
      {
        id: 'a',
        name: 'Bob',
        photoURL: 'https://randomuser.me/api/portraits/men/20.jpg',
      },
      {
        id: 'b',
        name: 'Tom',
        photoURL: 'https://randomuser.me/api/portraits/men/22.jpg',
      },
    ],
  },
];
